// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fitness_kernel_fitness_kernel_Pipeline_copy_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_vec_0_AWVALID,
        m_axi_gmem_vec_0_AWREADY,
        m_axi_gmem_vec_0_AWADDR,
        m_axi_gmem_vec_0_AWID,
        m_axi_gmem_vec_0_AWLEN,
        m_axi_gmem_vec_0_AWSIZE,
        m_axi_gmem_vec_0_AWBURST,
        m_axi_gmem_vec_0_AWLOCK,
        m_axi_gmem_vec_0_AWCACHE,
        m_axi_gmem_vec_0_AWPROT,
        m_axi_gmem_vec_0_AWQOS,
        m_axi_gmem_vec_0_AWREGION,
        m_axi_gmem_vec_0_AWUSER,
        m_axi_gmem_vec_0_WVALID,
        m_axi_gmem_vec_0_WREADY,
        m_axi_gmem_vec_0_WDATA,
        m_axi_gmem_vec_0_WSTRB,
        m_axi_gmem_vec_0_WLAST,
        m_axi_gmem_vec_0_WID,
        m_axi_gmem_vec_0_WUSER,
        m_axi_gmem_vec_0_ARVALID,
        m_axi_gmem_vec_0_ARREADY,
        m_axi_gmem_vec_0_ARADDR,
        m_axi_gmem_vec_0_ARID,
        m_axi_gmem_vec_0_ARLEN,
        m_axi_gmem_vec_0_ARSIZE,
        m_axi_gmem_vec_0_ARBURST,
        m_axi_gmem_vec_0_ARLOCK,
        m_axi_gmem_vec_0_ARCACHE,
        m_axi_gmem_vec_0_ARPROT,
        m_axi_gmem_vec_0_ARQOS,
        m_axi_gmem_vec_0_ARREGION,
        m_axi_gmem_vec_0_ARUSER,
        m_axi_gmem_vec_0_RVALID,
        m_axi_gmem_vec_0_RREADY,
        m_axi_gmem_vec_0_RDATA,
        m_axi_gmem_vec_0_RLAST,
        m_axi_gmem_vec_0_RID,
        m_axi_gmem_vec_0_RFIFONUM,
        m_axi_gmem_vec_0_RUSER,
        m_axi_gmem_vec_0_RRESP,
        m_axi_gmem_vec_0_BVALID,
        m_axi_gmem_vec_0_BREADY,
        m_axi_gmem_vec_0_BRESP,
        m_axi_gmem_vec_0_BID,
        m_axi_gmem_vec_0_BUSER,
        total,
        sext_ln59,
        local_vectors_address0,
        local_vectors_ce0,
        local_vectors_we0,
        local_vectors_d0,
        local_vectors_1_address0,
        local_vectors_1_ce0,
        local_vectors_1_we0,
        local_vectors_1_d0,
        local_vectors_2_address0,
        local_vectors_2_ce0,
        local_vectors_2_we0,
        local_vectors_2_d0,
        local_vectors_3_address0,
        local_vectors_3_ce0,
        local_vectors_3_we0,
        local_vectors_3_d0,
        local_vectors_4_address0,
        local_vectors_4_ce0,
        local_vectors_4_we0,
        local_vectors_4_d0,
        local_vectors_5_address0,
        local_vectors_5_ce0,
        local_vectors_5_we0,
        local_vectors_5_d0,
        local_vectors_6_address0,
        local_vectors_6_ce0,
        local_vectors_6_we0,
        local_vectors_6_d0,
        local_vectors_7_address0,
        local_vectors_7_ce0,
        local_vectors_7_we0,
        local_vectors_7_d0,
        local_vectors_8_address0,
        local_vectors_8_ce0,
        local_vectors_8_we0,
        local_vectors_8_d0,
        local_vectors_9_address0,
        local_vectors_9_ce0,
        local_vectors_9_we0,
        local_vectors_9_d0,
        p_ZZ14fitness_kernelE13local_vectors_10_address0,
        p_ZZ14fitness_kernelE13local_vectors_10_ce0,
        p_ZZ14fitness_kernelE13local_vectors_10_we0,
        p_ZZ14fitness_kernelE13local_vectors_10_d0,
        p_ZZ14fitness_kernelE13local_vectors_11_address0,
        p_ZZ14fitness_kernelE13local_vectors_11_ce0,
        p_ZZ14fitness_kernelE13local_vectors_11_we0,
        p_ZZ14fitness_kernelE13local_vectors_11_d0,
        p_ZZ14fitness_kernelE13local_vectors_12_address0,
        p_ZZ14fitness_kernelE13local_vectors_12_ce0,
        p_ZZ14fitness_kernelE13local_vectors_12_we0,
        p_ZZ14fitness_kernelE13local_vectors_12_d0,
        p_ZZ14fitness_kernelE13local_vectors_13_address0,
        p_ZZ14fitness_kernelE13local_vectors_13_ce0,
        p_ZZ14fitness_kernelE13local_vectors_13_we0,
        p_ZZ14fitness_kernelE13local_vectors_13_d0,
        p_ZZ14fitness_kernelE13local_vectors_14_address0,
        p_ZZ14fitness_kernelE13local_vectors_14_ce0,
        p_ZZ14fitness_kernelE13local_vectors_14_we0,
        p_ZZ14fitness_kernelE13local_vectors_14_d0,
        p_ZZ14fitness_kernelE13local_vectors_15_address0,
        p_ZZ14fitness_kernelE13local_vectors_15_ce0,
        p_ZZ14fitness_kernelE13local_vectors_15_we0,
        p_ZZ14fitness_kernelE13local_vectors_15_d0,
        p_ZZ14fitness_kernelE13local_vectors_16_address0,
        p_ZZ14fitness_kernelE13local_vectors_16_ce0,
        p_ZZ14fitness_kernelE13local_vectors_16_we0,
        p_ZZ14fitness_kernelE13local_vectors_16_d0,
        p_ZZ14fitness_kernelE13local_vectors_17_address0,
        p_ZZ14fitness_kernelE13local_vectors_17_ce0,
        p_ZZ14fitness_kernelE13local_vectors_17_we0,
        p_ZZ14fitness_kernelE13local_vectors_17_d0,
        p_ZZ14fitness_kernelE13local_vectors_18_address0,
        p_ZZ14fitness_kernelE13local_vectors_18_ce0,
        p_ZZ14fitness_kernelE13local_vectors_18_we0,
        p_ZZ14fitness_kernelE13local_vectors_18_d0,
        p_ZZ14fitness_kernelE13local_vectors_19_address0,
        p_ZZ14fitness_kernelE13local_vectors_19_ce0,
        p_ZZ14fitness_kernelE13local_vectors_19_we0,
        p_ZZ14fitness_kernelE13local_vectors_19_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_vec_0_AWVALID;
input   m_axi_gmem_vec_0_AWREADY;
output  [63:0] m_axi_gmem_vec_0_AWADDR;
output  [0:0] m_axi_gmem_vec_0_AWID;
output  [31:0] m_axi_gmem_vec_0_AWLEN;
output  [2:0] m_axi_gmem_vec_0_AWSIZE;
output  [1:0] m_axi_gmem_vec_0_AWBURST;
output  [1:0] m_axi_gmem_vec_0_AWLOCK;
output  [3:0] m_axi_gmem_vec_0_AWCACHE;
output  [2:0] m_axi_gmem_vec_0_AWPROT;
output  [3:0] m_axi_gmem_vec_0_AWQOS;
output  [3:0] m_axi_gmem_vec_0_AWREGION;
output  [0:0] m_axi_gmem_vec_0_AWUSER;
output   m_axi_gmem_vec_0_WVALID;
input   m_axi_gmem_vec_0_WREADY;
output  [31:0] m_axi_gmem_vec_0_WDATA;
output  [3:0] m_axi_gmem_vec_0_WSTRB;
output   m_axi_gmem_vec_0_WLAST;
output  [0:0] m_axi_gmem_vec_0_WID;
output  [0:0] m_axi_gmem_vec_0_WUSER;
output   m_axi_gmem_vec_0_ARVALID;
input   m_axi_gmem_vec_0_ARREADY;
output  [63:0] m_axi_gmem_vec_0_ARADDR;
output  [0:0] m_axi_gmem_vec_0_ARID;
output  [31:0] m_axi_gmem_vec_0_ARLEN;
output  [2:0] m_axi_gmem_vec_0_ARSIZE;
output  [1:0] m_axi_gmem_vec_0_ARBURST;
output  [1:0] m_axi_gmem_vec_0_ARLOCK;
output  [3:0] m_axi_gmem_vec_0_ARCACHE;
output  [2:0] m_axi_gmem_vec_0_ARPROT;
output  [3:0] m_axi_gmem_vec_0_ARQOS;
output  [3:0] m_axi_gmem_vec_0_ARREGION;
output  [0:0] m_axi_gmem_vec_0_ARUSER;
input   m_axi_gmem_vec_0_RVALID;
output   m_axi_gmem_vec_0_RREADY;
input  [31:0] m_axi_gmem_vec_0_RDATA;
input   m_axi_gmem_vec_0_RLAST;
input  [0:0] m_axi_gmem_vec_0_RID;
input  [8:0] m_axi_gmem_vec_0_RFIFONUM;
input  [0:0] m_axi_gmem_vec_0_RUSER;
input  [1:0] m_axi_gmem_vec_0_RRESP;
input   m_axi_gmem_vec_0_BVALID;
output   m_axi_gmem_vec_0_BREADY;
input  [1:0] m_axi_gmem_vec_0_BRESP;
input  [0:0] m_axi_gmem_vec_0_BID;
input  [0:0] m_axi_gmem_vec_0_BUSER;
input  [31:0] total;
input  [61:0] sext_ln59;
output  [8:0] local_vectors_address0;
output   local_vectors_ce0;
output   local_vectors_we0;
output  [31:0] local_vectors_d0;
output  [8:0] local_vectors_1_address0;
output   local_vectors_1_ce0;
output   local_vectors_1_we0;
output  [31:0] local_vectors_1_d0;
output  [8:0] local_vectors_2_address0;
output   local_vectors_2_ce0;
output   local_vectors_2_we0;
output  [31:0] local_vectors_2_d0;
output  [8:0] local_vectors_3_address0;
output   local_vectors_3_ce0;
output   local_vectors_3_we0;
output  [31:0] local_vectors_3_d0;
output  [8:0] local_vectors_4_address0;
output   local_vectors_4_ce0;
output   local_vectors_4_we0;
output  [31:0] local_vectors_4_d0;
output  [8:0] local_vectors_5_address0;
output   local_vectors_5_ce0;
output   local_vectors_5_we0;
output  [31:0] local_vectors_5_d0;
output  [8:0] local_vectors_6_address0;
output   local_vectors_6_ce0;
output   local_vectors_6_we0;
output  [31:0] local_vectors_6_d0;
output  [8:0] local_vectors_7_address0;
output   local_vectors_7_ce0;
output   local_vectors_7_we0;
output  [31:0] local_vectors_7_d0;
output  [8:0] local_vectors_8_address0;
output   local_vectors_8_ce0;
output   local_vectors_8_we0;
output  [31:0] local_vectors_8_d0;
output  [8:0] local_vectors_9_address0;
output   local_vectors_9_ce0;
output   local_vectors_9_we0;
output  [31:0] local_vectors_9_d0;
output  [8:0] p_ZZ14fitness_kernelE13local_vectors_10_address0;
output   p_ZZ14fitness_kernelE13local_vectors_10_ce0;
output   p_ZZ14fitness_kernelE13local_vectors_10_we0;
output  [31:0] p_ZZ14fitness_kernelE13local_vectors_10_d0;
output  [8:0] p_ZZ14fitness_kernelE13local_vectors_11_address0;
output   p_ZZ14fitness_kernelE13local_vectors_11_ce0;
output   p_ZZ14fitness_kernelE13local_vectors_11_we0;
output  [31:0] p_ZZ14fitness_kernelE13local_vectors_11_d0;
output  [8:0] p_ZZ14fitness_kernelE13local_vectors_12_address0;
output   p_ZZ14fitness_kernelE13local_vectors_12_ce0;
output   p_ZZ14fitness_kernelE13local_vectors_12_we0;
output  [31:0] p_ZZ14fitness_kernelE13local_vectors_12_d0;
output  [8:0] p_ZZ14fitness_kernelE13local_vectors_13_address0;
output   p_ZZ14fitness_kernelE13local_vectors_13_ce0;
output   p_ZZ14fitness_kernelE13local_vectors_13_we0;
output  [31:0] p_ZZ14fitness_kernelE13local_vectors_13_d0;
output  [8:0] p_ZZ14fitness_kernelE13local_vectors_14_address0;
output   p_ZZ14fitness_kernelE13local_vectors_14_ce0;
output   p_ZZ14fitness_kernelE13local_vectors_14_we0;
output  [31:0] p_ZZ14fitness_kernelE13local_vectors_14_d0;
output  [8:0] p_ZZ14fitness_kernelE13local_vectors_15_address0;
output   p_ZZ14fitness_kernelE13local_vectors_15_ce0;
output   p_ZZ14fitness_kernelE13local_vectors_15_we0;
output  [31:0] p_ZZ14fitness_kernelE13local_vectors_15_d0;
output  [8:0] p_ZZ14fitness_kernelE13local_vectors_16_address0;
output   p_ZZ14fitness_kernelE13local_vectors_16_ce0;
output   p_ZZ14fitness_kernelE13local_vectors_16_we0;
output  [31:0] p_ZZ14fitness_kernelE13local_vectors_16_d0;
output  [8:0] p_ZZ14fitness_kernelE13local_vectors_17_address0;
output   p_ZZ14fitness_kernelE13local_vectors_17_ce0;
output   p_ZZ14fitness_kernelE13local_vectors_17_we0;
output  [31:0] p_ZZ14fitness_kernelE13local_vectors_17_d0;
output  [8:0] p_ZZ14fitness_kernelE13local_vectors_18_address0;
output   p_ZZ14fitness_kernelE13local_vectors_18_ce0;
output   p_ZZ14fitness_kernelE13local_vectors_18_we0;
output  [31:0] p_ZZ14fitness_kernelE13local_vectors_18_d0;
output  [8:0] p_ZZ14fitness_kernelE13local_vectors_19_address0;
output   p_ZZ14fitness_kernelE13local_vectors_19_ce0;
output   p_ZZ14fitness_kernelE13local_vectors_19_we0;
output  [31:0] p_ZZ14fitness_kernelE13local_vectors_19_d0;

reg ap_idle;
reg m_axi_gmem_vec_0_RREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln59_fu_462_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_vec_blk_n_R;
wire    ap_block_pp0_stage0_grp1;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [4:0] trunc_ln59_fu_473_p1;
reg   [4:0] trunc_ln59_reg_600;
wire   [31:0] bitcast_ln61_fu_513_p1;
reg   [31:0] bitcast_ln61_reg_604;
wire   [63:0] zext_ln59_1_fu_536_p1;
wire    ap_block_pp0_stage0_grp0;
reg   [30:0] phi_urem_fu_144;
wire   [30:0] select_ln59_fu_489_p3;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
reg   [62:0] phi_mul_fu_148;
wire   [62:0] add_ln59_1_fu_520_p2;
reg   [30:0] i_fu_152;
wire   [30:0] add_ln59_fu_467_p2;
reg    p_ZZ14fitness_kernelE13local_vectors_18_we0_local;
reg    ap_predicate_pred339_state4;
reg    p_ZZ14fitness_kernelE13local_vectors_18_ce0_local;
reg    p_ZZ14fitness_kernelE13local_vectors_17_we0_local;
reg    ap_predicate_pred353_state4;
reg    p_ZZ14fitness_kernelE13local_vectors_17_ce0_local;
reg    p_ZZ14fitness_kernelE13local_vectors_16_we0_local;
reg    ap_predicate_pred367_state4;
reg    p_ZZ14fitness_kernelE13local_vectors_16_ce0_local;
reg    p_ZZ14fitness_kernelE13local_vectors_15_we0_local;
reg    ap_predicate_pred381_state4;
reg    p_ZZ14fitness_kernelE13local_vectors_15_ce0_local;
reg    p_ZZ14fitness_kernelE13local_vectors_14_we0_local;
reg    ap_predicate_pred395_state4;
reg    p_ZZ14fitness_kernelE13local_vectors_14_ce0_local;
reg    p_ZZ14fitness_kernelE13local_vectors_13_we0_local;
reg    ap_predicate_pred409_state4;
reg    p_ZZ14fitness_kernelE13local_vectors_13_ce0_local;
reg    p_ZZ14fitness_kernelE13local_vectors_12_we0_local;
reg    ap_predicate_pred423_state4;
reg    p_ZZ14fitness_kernelE13local_vectors_12_ce0_local;
reg    p_ZZ14fitness_kernelE13local_vectors_11_we0_local;
reg    ap_predicate_pred437_state4;
reg    p_ZZ14fitness_kernelE13local_vectors_11_ce0_local;
reg    p_ZZ14fitness_kernelE13local_vectors_10_we0_local;
reg    ap_predicate_pred451_state4;
reg    p_ZZ14fitness_kernelE13local_vectors_10_ce0_local;
reg    local_vectors_9_we0_local;
reg    ap_predicate_pred465_state4;
reg    local_vectors_9_ce0_local;
reg    local_vectors_8_we0_local;
reg    ap_predicate_pred479_state4;
reg    local_vectors_8_ce0_local;
reg    local_vectors_7_we0_local;
reg    ap_predicate_pred493_state4;
reg    local_vectors_7_ce0_local;
reg    local_vectors_6_we0_local;
reg    ap_predicate_pred507_state4;
reg    local_vectors_6_ce0_local;
reg    local_vectors_5_we0_local;
reg    ap_predicate_pred521_state4;
reg    local_vectors_5_ce0_local;
reg    local_vectors_4_we0_local;
reg    ap_predicate_pred535_state4;
reg    local_vectors_4_ce0_local;
reg    local_vectors_3_we0_local;
reg    ap_predicate_pred549_state4;
reg    local_vectors_3_ce0_local;
reg    local_vectors_2_we0_local;
reg    ap_predicate_pred563_state4;
reg    local_vectors_2_ce0_local;
reg    local_vectors_1_we0_local;
reg    ap_predicate_pred577_state4;
reg    local_vectors_1_ce0_local;
reg    local_vectors_we0_local;
reg    ap_predicate_pred591_state4;
reg    local_vectors_ce0_local;
reg    p_ZZ14fitness_kernelE13local_vectors_19_we0_local;
reg    ap_predicate_pred640_state4;
reg    p_ZZ14fitness_kernelE13local_vectors_19_ce0_local;
wire   [31:0] zext_ln59_fu_458_p1;
wire   [0:0] icmp_ln59_1_fu_483_p2;
wire   [30:0] add_ln59_2_fu_477_p2;
wire   [26:0] tmp_fu_526_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 phi_urem_fu_144 = 31'd0;
#0 phi_mul_fu_148 = 63'd0;
#0 i_fu_152 = 31'd0;
#0 ap_done_reg = 1'b0;
end

fitness_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_152 <= 31'd0;
        end else if (((icmp_ln59_fu_462_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            i_fu_152 <= add_ln59_fu_467_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            phi_mul_fu_148 <= 63'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            phi_mul_fu_148 <= add_ln59_1_fu_520_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            phi_urem_fu_144 <= 31'd0;
        end else if (((icmp_ln59_fu_462_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            phi_urem_fu_144 <= select_ln59_fu_489_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        trunc_ln59_reg_600 <= trunc_ln59_fu_473_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_predicate_pred339_state4 <= (trunc_ln59_reg_600 == 5'd18);
        ap_predicate_pred353_state4 <= (trunc_ln59_reg_600 == 5'd17);
        ap_predicate_pred367_state4 <= (trunc_ln59_reg_600 == 5'd16);
        ap_predicate_pred381_state4 <= (trunc_ln59_reg_600 == 5'd15);
        ap_predicate_pred395_state4 <= (trunc_ln59_reg_600 == 5'd14);
        ap_predicate_pred409_state4 <= (trunc_ln59_reg_600 == 5'd13);
        ap_predicate_pred423_state4 <= (trunc_ln59_reg_600 == 5'd12);
        ap_predicate_pred437_state4 <= (trunc_ln59_reg_600 == 5'd11);
        ap_predicate_pred451_state4 <= (trunc_ln59_reg_600 == 5'd10);
        ap_predicate_pred465_state4 <= (trunc_ln59_reg_600 == 5'd9);
        ap_predicate_pred479_state4 <= (trunc_ln59_reg_600 == 5'd8);
        ap_predicate_pred493_state4 <= (trunc_ln59_reg_600 == 5'd7);
        ap_predicate_pred507_state4 <= (trunc_ln59_reg_600 == 5'd6);
        ap_predicate_pred521_state4 <= (trunc_ln59_reg_600 == 5'd5);
        ap_predicate_pred535_state4 <= (trunc_ln59_reg_600 == 5'd4);
        ap_predicate_pred549_state4 <= (trunc_ln59_reg_600 == 5'd3);
        ap_predicate_pred563_state4 <= (trunc_ln59_reg_600 == 5'd2);
        ap_predicate_pred577_state4 <= (trunc_ln59_reg_600 == 5'd1);
        ap_predicate_pred591_state4 <= (trunc_ln59_reg_600 == 5'd0);
        ap_predicate_pred640_state4 <= (~(trunc_ln59_reg_600 == 5'd0) & ~(trunc_ln59_reg_600 == 5'd1) & ~(trunc_ln59_reg_600 == 5'd2) & ~(trunc_ln59_reg_600 == 5'd3) & ~(trunc_ln59_reg_600 == 5'd4) & ~(trunc_ln59_reg_600 == 5'd5) & ~(trunc_ln59_reg_600 == 5'd6) & ~(trunc_ln59_reg_600 == 5'd7) & ~(trunc_ln59_reg_600 == 5'd8) & ~(trunc_ln59_reg_600 == 5'd9) & ~(trunc_ln59_reg_600 == 5'd10) & ~(trunc_ln59_reg_600 == 5'd11) & ~(trunc_ln59_reg_600 == 5'd12) & ~(trunc_ln59_reg_600 == 5'd13) & ~(trunc_ln59_reg_600 == 5'd14) & ~(trunc_ln59_reg_600 == 5'd15) & ~(trunc_ln59_reg_600 == 5'd16) & ~(trunc_ln59_reg_600 == 5'd17) & ~(trunc_ln59_reg_600 == 5'd18));
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        bitcast_ln61_reg_604 <= bitcast_ln61_fu_513_p1;
    end
end

always @ (*) begin
    if (((icmp_ln59_fu_462_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        gmem_vec_blk_n_R = m_axi_gmem_vec_0_RVALID;
    end else begin
        gmem_vec_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        local_vectors_1_ce0_local = 1'b1;
    end else begin
        local_vectors_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_predicate_pred577_state4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        local_vectors_1_we0_local = 1'b1;
    end else begin
        local_vectors_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        local_vectors_2_ce0_local = 1'b1;
    end else begin
        local_vectors_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_predicate_pred563_state4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        local_vectors_2_we0_local = 1'b1;
    end else begin
        local_vectors_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        local_vectors_3_ce0_local = 1'b1;
    end else begin
        local_vectors_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_predicate_pred549_state4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        local_vectors_3_we0_local = 1'b1;
    end else begin
        local_vectors_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        local_vectors_4_ce0_local = 1'b1;
    end else begin
        local_vectors_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_predicate_pred535_state4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        local_vectors_4_we0_local = 1'b1;
    end else begin
        local_vectors_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        local_vectors_5_ce0_local = 1'b1;
    end else begin
        local_vectors_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_predicate_pred521_state4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        local_vectors_5_we0_local = 1'b1;
    end else begin
        local_vectors_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        local_vectors_6_ce0_local = 1'b1;
    end else begin
        local_vectors_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_predicate_pred507_state4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        local_vectors_6_we0_local = 1'b1;
    end else begin
        local_vectors_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        local_vectors_7_ce0_local = 1'b1;
    end else begin
        local_vectors_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_predicate_pred493_state4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        local_vectors_7_we0_local = 1'b1;
    end else begin
        local_vectors_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        local_vectors_8_ce0_local = 1'b1;
    end else begin
        local_vectors_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_predicate_pred479_state4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        local_vectors_8_we0_local = 1'b1;
    end else begin
        local_vectors_8_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        local_vectors_9_ce0_local = 1'b1;
    end else begin
        local_vectors_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_predicate_pred465_state4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        local_vectors_9_we0_local = 1'b1;
    end else begin
        local_vectors_9_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        local_vectors_ce0_local = 1'b1;
    end else begin
        local_vectors_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_predicate_pred591_state4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        local_vectors_we0_local = 1'b1;
    end else begin
        local_vectors_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        m_axi_gmem_vec_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem_vec_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZZ14fitness_kernelE13local_vectors_10_ce0_local = 1'b1;
    end else begin
        p_ZZ14fitness_kernelE13local_vectors_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_predicate_pred451_state4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZZ14fitness_kernelE13local_vectors_10_we0_local = 1'b1;
    end else begin
        p_ZZ14fitness_kernelE13local_vectors_10_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZZ14fitness_kernelE13local_vectors_11_ce0_local = 1'b1;
    end else begin
        p_ZZ14fitness_kernelE13local_vectors_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_predicate_pred437_state4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZZ14fitness_kernelE13local_vectors_11_we0_local = 1'b1;
    end else begin
        p_ZZ14fitness_kernelE13local_vectors_11_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZZ14fitness_kernelE13local_vectors_12_ce0_local = 1'b1;
    end else begin
        p_ZZ14fitness_kernelE13local_vectors_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_predicate_pred423_state4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZZ14fitness_kernelE13local_vectors_12_we0_local = 1'b1;
    end else begin
        p_ZZ14fitness_kernelE13local_vectors_12_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZZ14fitness_kernelE13local_vectors_13_ce0_local = 1'b1;
    end else begin
        p_ZZ14fitness_kernelE13local_vectors_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_predicate_pred409_state4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZZ14fitness_kernelE13local_vectors_13_we0_local = 1'b1;
    end else begin
        p_ZZ14fitness_kernelE13local_vectors_13_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZZ14fitness_kernelE13local_vectors_14_ce0_local = 1'b1;
    end else begin
        p_ZZ14fitness_kernelE13local_vectors_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_predicate_pred395_state4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZZ14fitness_kernelE13local_vectors_14_we0_local = 1'b1;
    end else begin
        p_ZZ14fitness_kernelE13local_vectors_14_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZZ14fitness_kernelE13local_vectors_15_ce0_local = 1'b1;
    end else begin
        p_ZZ14fitness_kernelE13local_vectors_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_predicate_pred381_state4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZZ14fitness_kernelE13local_vectors_15_we0_local = 1'b1;
    end else begin
        p_ZZ14fitness_kernelE13local_vectors_15_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZZ14fitness_kernelE13local_vectors_16_ce0_local = 1'b1;
    end else begin
        p_ZZ14fitness_kernelE13local_vectors_16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_predicate_pred367_state4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZZ14fitness_kernelE13local_vectors_16_we0_local = 1'b1;
    end else begin
        p_ZZ14fitness_kernelE13local_vectors_16_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZZ14fitness_kernelE13local_vectors_17_ce0_local = 1'b1;
    end else begin
        p_ZZ14fitness_kernelE13local_vectors_17_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_predicate_pred353_state4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZZ14fitness_kernelE13local_vectors_17_we0_local = 1'b1;
    end else begin
        p_ZZ14fitness_kernelE13local_vectors_17_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZZ14fitness_kernelE13local_vectors_18_ce0_local = 1'b1;
    end else begin
        p_ZZ14fitness_kernelE13local_vectors_18_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_predicate_pred339_state4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZZ14fitness_kernelE13local_vectors_18_we0_local = 1'b1;
    end else begin
        p_ZZ14fitness_kernelE13local_vectors_18_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZZ14fitness_kernelE13local_vectors_19_ce0_local = 1'b1;
    end else begin
        p_ZZ14fitness_kernelE13local_vectors_19_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_predicate_pred640_state4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZZ14fitness_kernelE13local_vectors_19_we0_local = 1'b1;
    end else begin
        p_ZZ14fitness_kernelE13local_vectors_19_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln59_1_fu_520_p2 = (phi_mul_fu_148 + 63'd3435973837);

assign add_ln59_2_fu_477_p2 = (phi_urem_fu_144 + 31'd1);

assign add_ln59_fu_467_p2 = (i_fu_152 + 31'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((m_axi_gmem_vec_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((m_axi_gmem_vec_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((m_axi_gmem_vec_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign bitcast_ln61_fu_513_p1 = m_axi_gmem_vec_0_RDATA;

assign icmp_ln59_1_fu_483_p2 = ((phi_urem_fu_144 == 31'd19) ? 1'b1 : 1'b0);

assign icmp_ln59_fu_462_p2 = (($signed(zext_ln59_fu_458_p1) < $signed(total)) ? 1'b1 : 1'b0);

assign local_vectors_1_address0 = zext_ln59_1_fu_536_p1;

assign local_vectors_1_ce0 = local_vectors_1_ce0_local;

assign local_vectors_1_d0 = bitcast_ln61_reg_604;

assign local_vectors_1_we0 = local_vectors_1_we0_local;

assign local_vectors_2_address0 = zext_ln59_1_fu_536_p1;

assign local_vectors_2_ce0 = local_vectors_2_ce0_local;

assign local_vectors_2_d0 = bitcast_ln61_reg_604;

assign local_vectors_2_we0 = local_vectors_2_we0_local;

assign local_vectors_3_address0 = zext_ln59_1_fu_536_p1;

assign local_vectors_3_ce0 = local_vectors_3_ce0_local;

assign local_vectors_3_d0 = bitcast_ln61_reg_604;

assign local_vectors_3_we0 = local_vectors_3_we0_local;

assign local_vectors_4_address0 = zext_ln59_1_fu_536_p1;

assign local_vectors_4_ce0 = local_vectors_4_ce0_local;

assign local_vectors_4_d0 = bitcast_ln61_reg_604;

assign local_vectors_4_we0 = local_vectors_4_we0_local;

assign local_vectors_5_address0 = zext_ln59_1_fu_536_p1;

assign local_vectors_5_ce0 = local_vectors_5_ce0_local;

assign local_vectors_5_d0 = bitcast_ln61_reg_604;

assign local_vectors_5_we0 = local_vectors_5_we0_local;

assign local_vectors_6_address0 = zext_ln59_1_fu_536_p1;

assign local_vectors_6_ce0 = local_vectors_6_ce0_local;

assign local_vectors_6_d0 = bitcast_ln61_reg_604;

assign local_vectors_6_we0 = local_vectors_6_we0_local;

assign local_vectors_7_address0 = zext_ln59_1_fu_536_p1;

assign local_vectors_7_ce0 = local_vectors_7_ce0_local;

assign local_vectors_7_d0 = bitcast_ln61_reg_604;

assign local_vectors_7_we0 = local_vectors_7_we0_local;

assign local_vectors_8_address0 = zext_ln59_1_fu_536_p1;

assign local_vectors_8_ce0 = local_vectors_8_ce0_local;

assign local_vectors_8_d0 = bitcast_ln61_reg_604;

assign local_vectors_8_we0 = local_vectors_8_we0_local;

assign local_vectors_9_address0 = zext_ln59_1_fu_536_p1;

assign local_vectors_9_ce0 = local_vectors_9_ce0_local;

assign local_vectors_9_d0 = bitcast_ln61_reg_604;

assign local_vectors_9_we0 = local_vectors_9_we0_local;

assign local_vectors_address0 = zext_ln59_1_fu_536_p1;

assign local_vectors_ce0 = local_vectors_ce0_local;

assign local_vectors_d0 = bitcast_ln61_reg_604;

assign local_vectors_we0 = local_vectors_we0_local;

assign m_axi_gmem_vec_0_ARADDR = 64'd0;

assign m_axi_gmem_vec_0_ARBURST = 2'd0;

assign m_axi_gmem_vec_0_ARCACHE = 4'd0;

assign m_axi_gmem_vec_0_ARID = 1'd0;

assign m_axi_gmem_vec_0_ARLEN = 32'd0;

assign m_axi_gmem_vec_0_ARLOCK = 2'd0;

assign m_axi_gmem_vec_0_ARPROT = 3'd0;

assign m_axi_gmem_vec_0_ARQOS = 4'd0;

assign m_axi_gmem_vec_0_ARREGION = 4'd0;

assign m_axi_gmem_vec_0_ARSIZE = 3'd0;

assign m_axi_gmem_vec_0_ARUSER = 1'd0;

assign m_axi_gmem_vec_0_ARVALID = 1'b0;

assign m_axi_gmem_vec_0_AWADDR = 64'd0;

assign m_axi_gmem_vec_0_AWBURST = 2'd0;

assign m_axi_gmem_vec_0_AWCACHE = 4'd0;

assign m_axi_gmem_vec_0_AWID = 1'd0;

assign m_axi_gmem_vec_0_AWLEN = 32'd0;

assign m_axi_gmem_vec_0_AWLOCK = 2'd0;

assign m_axi_gmem_vec_0_AWPROT = 3'd0;

assign m_axi_gmem_vec_0_AWQOS = 4'd0;

assign m_axi_gmem_vec_0_AWREGION = 4'd0;

assign m_axi_gmem_vec_0_AWSIZE = 3'd0;

assign m_axi_gmem_vec_0_AWUSER = 1'd0;

assign m_axi_gmem_vec_0_AWVALID = 1'b0;

assign m_axi_gmem_vec_0_BREADY = 1'b0;

assign m_axi_gmem_vec_0_WDATA = 32'd0;

assign m_axi_gmem_vec_0_WID = 1'd0;

assign m_axi_gmem_vec_0_WLAST = 1'b0;

assign m_axi_gmem_vec_0_WSTRB = 4'd0;

assign m_axi_gmem_vec_0_WUSER = 1'd0;

assign m_axi_gmem_vec_0_WVALID = 1'b0;

assign p_ZZ14fitness_kernelE13local_vectors_10_address0 = zext_ln59_1_fu_536_p1;

assign p_ZZ14fitness_kernelE13local_vectors_10_ce0 = p_ZZ14fitness_kernelE13local_vectors_10_ce0_local;

assign p_ZZ14fitness_kernelE13local_vectors_10_d0 = bitcast_ln61_reg_604;

assign p_ZZ14fitness_kernelE13local_vectors_10_we0 = p_ZZ14fitness_kernelE13local_vectors_10_we0_local;

assign p_ZZ14fitness_kernelE13local_vectors_11_address0 = zext_ln59_1_fu_536_p1;

assign p_ZZ14fitness_kernelE13local_vectors_11_ce0 = p_ZZ14fitness_kernelE13local_vectors_11_ce0_local;

assign p_ZZ14fitness_kernelE13local_vectors_11_d0 = bitcast_ln61_reg_604;

assign p_ZZ14fitness_kernelE13local_vectors_11_we0 = p_ZZ14fitness_kernelE13local_vectors_11_we0_local;

assign p_ZZ14fitness_kernelE13local_vectors_12_address0 = zext_ln59_1_fu_536_p1;

assign p_ZZ14fitness_kernelE13local_vectors_12_ce0 = p_ZZ14fitness_kernelE13local_vectors_12_ce0_local;

assign p_ZZ14fitness_kernelE13local_vectors_12_d0 = bitcast_ln61_reg_604;

assign p_ZZ14fitness_kernelE13local_vectors_12_we0 = p_ZZ14fitness_kernelE13local_vectors_12_we0_local;

assign p_ZZ14fitness_kernelE13local_vectors_13_address0 = zext_ln59_1_fu_536_p1;

assign p_ZZ14fitness_kernelE13local_vectors_13_ce0 = p_ZZ14fitness_kernelE13local_vectors_13_ce0_local;

assign p_ZZ14fitness_kernelE13local_vectors_13_d0 = bitcast_ln61_reg_604;

assign p_ZZ14fitness_kernelE13local_vectors_13_we0 = p_ZZ14fitness_kernelE13local_vectors_13_we0_local;

assign p_ZZ14fitness_kernelE13local_vectors_14_address0 = zext_ln59_1_fu_536_p1;

assign p_ZZ14fitness_kernelE13local_vectors_14_ce0 = p_ZZ14fitness_kernelE13local_vectors_14_ce0_local;

assign p_ZZ14fitness_kernelE13local_vectors_14_d0 = bitcast_ln61_reg_604;

assign p_ZZ14fitness_kernelE13local_vectors_14_we0 = p_ZZ14fitness_kernelE13local_vectors_14_we0_local;

assign p_ZZ14fitness_kernelE13local_vectors_15_address0 = zext_ln59_1_fu_536_p1;

assign p_ZZ14fitness_kernelE13local_vectors_15_ce0 = p_ZZ14fitness_kernelE13local_vectors_15_ce0_local;

assign p_ZZ14fitness_kernelE13local_vectors_15_d0 = bitcast_ln61_reg_604;

assign p_ZZ14fitness_kernelE13local_vectors_15_we0 = p_ZZ14fitness_kernelE13local_vectors_15_we0_local;

assign p_ZZ14fitness_kernelE13local_vectors_16_address0 = zext_ln59_1_fu_536_p1;

assign p_ZZ14fitness_kernelE13local_vectors_16_ce0 = p_ZZ14fitness_kernelE13local_vectors_16_ce0_local;

assign p_ZZ14fitness_kernelE13local_vectors_16_d0 = bitcast_ln61_reg_604;

assign p_ZZ14fitness_kernelE13local_vectors_16_we0 = p_ZZ14fitness_kernelE13local_vectors_16_we0_local;

assign p_ZZ14fitness_kernelE13local_vectors_17_address0 = zext_ln59_1_fu_536_p1;

assign p_ZZ14fitness_kernelE13local_vectors_17_ce0 = p_ZZ14fitness_kernelE13local_vectors_17_ce0_local;

assign p_ZZ14fitness_kernelE13local_vectors_17_d0 = bitcast_ln61_reg_604;

assign p_ZZ14fitness_kernelE13local_vectors_17_we0 = p_ZZ14fitness_kernelE13local_vectors_17_we0_local;

assign p_ZZ14fitness_kernelE13local_vectors_18_address0 = zext_ln59_1_fu_536_p1;

assign p_ZZ14fitness_kernelE13local_vectors_18_ce0 = p_ZZ14fitness_kernelE13local_vectors_18_ce0_local;

assign p_ZZ14fitness_kernelE13local_vectors_18_d0 = bitcast_ln61_reg_604;

assign p_ZZ14fitness_kernelE13local_vectors_18_we0 = p_ZZ14fitness_kernelE13local_vectors_18_we0_local;

assign p_ZZ14fitness_kernelE13local_vectors_19_address0 = zext_ln59_1_fu_536_p1;

assign p_ZZ14fitness_kernelE13local_vectors_19_ce0 = p_ZZ14fitness_kernelE13local_vectors_19_ce0_local;

assign p_ZZ14fitness_kernelE13local_vectors_19_d0 = bitcast_ln61_reg_604;

assign p_ZZ14fitness_kernelE13local_vectors_19_we0 = p_ZZ14fitness_kernelE13local_vectors_19_we0_local;

assign select_ln59_fu_489_p3 = ((icmp_ln59_1_fu_483_p2[0:0] == 1'b1) ? 31'd0 : add_ln59_2_fu_477_p2);

assign tmp_fu_526_p4 = {{phi_mul_fu_148[62:36]}};

assign trunc_ln59_fu_473_p1 = phi_urem_fu_144[4:0];

assign zext_ln59_1_fu_536_p1 = tmp_fu_526_p4;

assign zext_ln59_fu_458_p1 = i_fu_152;

endmodule //fitness_kernel_fitness_kernel_Pipeline_copy_loop
