-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fitness_kernel_fitness_kernel_Pipeline_copy_loop is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem_vec_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_vec_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem_vec_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_vec_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_vec_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_vec_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_vec_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_vec_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_vec_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_vec_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_vec_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_vec_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_vec_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_vec_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem_vec_0_WREADY : IN STD_LOGIC;
    m_axi_gmem_vec_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_vec_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_vec_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem_vec_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_vec_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_vec_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_vec_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem_vec_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_vec_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_vec_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_vec_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_vec_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_vec_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_vec_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_vec_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_vec_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_vec_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_vec_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_vec_0_RVALID : IN STD_LOGIC;
    m_axi_gmem_vec_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem_vec_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_vec_0_RLAST : IN STD_LOGIC;
    m_axi_gmem_vec_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_vec_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem_vec_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_vec_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_vec_0_BVALID : IN STD_LOGIC;
    m_axi_gmem_vec_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem_vec_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_vec_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_vec_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    total : IN STD_LOGIC_VECTOR (31 downto 0);
    sext_ln59 : IN STD_LOGIC_VECTOR (61 downto 0);
    local_vectors_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    local_vectors_ce0 : OUT STD_LOGIC;
    local_vectors_we0 : OUT STD_LOGIC;
    local_vectors_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_vectors_1_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    local_vectors_1_ce0 : OUT STD_LOGIC;
    local_vectors_1_we0 : OUT STD_LOGIC;
    local_vectors_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_vectors_2_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    local_vectors_2_ce0 : OUT STD_LOGIC;
    local_vectors_2_we0 : OUT STD_LOGIC;
    local_vectors_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_vectors_3_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    local_vectors_3_ce0 : OUT STD_LOGIC;
    local_vectors_3_we0 : OUT STD_LOGIC;
    local_vectors_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_vectors_4_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    local_vectors_4_ce0 : OUT STD_LOGIC;
    local_vectors_4_we0 : OUT STD_LOGIC;
    local_vectors_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_vectors_5_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    local_vectors_5_ce0 : OUT STD_LOGIC;
    local_vectors_5_we0 : OUT STD_LOGIC;
    local_vectors_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_vectors_6_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    local_vectors_6_ce0 : OUT STD_LOGIC;
    local_vectors_6_we0 : OUT STD_LOGIC;
    local_vectors_6_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_vectors_7_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    local_vectors_7_ce0 : OUT STD_LOGIC;
    local_vectors_7_we0 : OUT STD_LOGIC;
    local_vectors_7_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_vectors_8_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    local_vectors_8_ce0 : OUT STD_LOGIC;
    local_vectors_8_we0 : OUT STD_LOGIC;
    local_vectors_8_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_vectors_9_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    local_vectors_9_ce0 : OUT STD_LOGIC;
    local_vectors_9_we0 : OUT STD_LOGIC;
    local_vectors_9_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ14fitness_kernelE13local_vectors_10_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZZ14fitness_kernelE13local_vectors_10_ce0 : OUT STD_LOGIC;
    p_ZZ14fitness_kernelE13local_vectors_10_we0 : OUT STD_LOGIC;
    p_ZZ14fitness_kernelE13local_vectors_10_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ14fitness_kernelE13local_vectors_11_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZZ14fitness_kernelE13local_vectors_11_ce0 : OUT STD_LOGIC;
    p_ZZ14fitness_kernelE13local_vectors_11_we0 : OUT STD_LOGIC;
    p_ZZ14fitness_kernelE13local_vectors_11_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ14fitness_kernelE13local_vectors_12_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZZ14fitness_kernelE13local_vectors_12_ce0 : OUT STD_LOGIC;
    p_ZZ14fitness_kernelE13local_vectors_12_we0 : OUT STD_LOGIC;
    p_ZZ14fitness_kernelE13local_vectors_12_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ14fitness_kernelE13local_vectors_13_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZZ14fitness_kernelE13local_vectors_13_ce0 : OUT STD_LOGIC;
    p_ZZ14fitness_kernelE13local_vectors_13_we0 : OUT STD_LOGIC;
    p_ZZ14fitness_kernelE13local_vectors_13_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ14fitness_kernelE13local_vectors_14_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZZ14fitness_kernelE13local_vectors_14_ce0 : OUT STD_LOGIC;
    p_ZZ14fitness_kernelE13local_vectors_14_we0 : OUT STD_LOGIC;
    p_ZZ14fitness_kernelE13local_vectors_14_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ14fitness_kernelE13local_vectors_15_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZZ14fitness_kernelE13local_vectors_15_ce0 : OUT STD_LOGIC;
    p_ZZ14fitness_kernelE13local_vectors_15_we0 : OUT STD_LOGIC;
    p_ZZ14fitness_kernelE13local_vectors_15_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ14fitness_kernelE13local_vectors_16_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZZ14fitness_kernelE13local_vectors_16_ce0 : OUT STD_LOGIC;
    p_ZZ14fitness_kernelE13local_vectors_16_we0 : OUT STD_LOGIC;
    p_ZZ14fitness_kernelE13local_vectors_16_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ14fitness_kernelE13local_vectors_17_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZZ14fitness_kernelE13local_vectors_17_ce0 : OUT STD_LOGIC;
    p_ZZ14fitness_kernelE13local_vectors_17_we0 : OUT STD_LOGIC;
    p_ZZ14fitness_kernelE13local_vectors_17_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ14fitness_kernelE13local_vectors_18_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZZ14fitness_kernelE13local_vectors_18_ce0 : OUT STD_LOGIC;
    p_ZZ14fitness_kernelE13local_vectors_18_we0 : OUT STD_LOGIC;
    p_ZZ14fitness_kernelE13local_vectors_18_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ14fitness_kernelE13local_vectors_19_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZZ14fitness_kernelE13local_vectors_19_ce0 : OUT STD_LOGIC;
    p_ZZ14fitness_kernelE13local_vectors_19_we0 : OUT STD_LOGIC;
    p_ZZ14fitness_kernelE13local_vectors_19_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of fitness_kernel_fitness_kernel_Pipeline_copy_loop is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv63_0 : STD_LOGIC_VECTOR (62 downto 0) := "000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv5_12 : STD_LOGIC_VECTOR (4 downto 0) := "10010";
    constant ap_const_lv5_11 : STD_LOGIC_VECTOR (4 downto 0) := "10001";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_F : STD_LOGIC_VECTOR (4 downto 0) := "01111";
    constant ap_const_lv5_E : STD_LOGIC_VECTOR (4 downto 0) := "01110";
    constant ap_const_lv5_D : STD_LOGIC_VECTOR (4 downto 0) := "01101";
    constant ap_const_lv5_C : STD_LOGIC_VECTOR (4 downto 0) := "01100";
    constant ap_const_lv5_B : STD_LOGIC_VECTOR (4 downto 0) := "01011";
    constant ap_const_lv5_A : STD_LOGIC_VECTOR (4 downto 0) := "01010";
    constant ap_const_lv5_9 : STD_LOGIC_VECTOR (4 downto 0) := "01001";
    constant ap_const_lv5_8 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_const_lv5_7 : STD_LOGIC_VECTOR (4 downto 0) := "00111";
    constant ap_const_lv5_6 : STD_LOGIC_VECTOR (4 downto 0) := "00110";
    constant ap_const_lv5_5 : STD_LOGIC_VECTOR (4 downto 0) := "00101";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv31_13 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000010011";
    constant ap_const_lv63_CCCCCCCD : STD_LOGIC_VECTOR (62 downto 0) := "000000000000000000000000000000011001100110011001100110011001101";
    constant ap_const_lv32_24 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100100";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln59_fu_462_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem_vec_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal trunc_ln59_fu_473_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln59_reg_600 : STD_LOGIC_VECTOR (4 downto 0);
    signal bitcast_ln61_fu_513_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln61_reg_604 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln59_1_fu_536_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_grp0 : BOOLEAN;
    signal phi_urem_fu_144 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal select_ln59_fu_489_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal phi_mul_fu_148 : STD_LOGIC_VECTOR (62 downto 0) := "000000000000000000000000000000000000000000000000000000000000000";
    signal add_ln59_1_fu_520_p2 : STD_LOGIC_VECTOR (62 downto 0);
    signal i_fu_152 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal add_ln59_fu_467_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal p_ZZ14fitness_kernelE13local_vectors_18_we0_local : STD_LOGIC;
    signal ap_predicate_pred339_state4 : BOOLEAN;
    signal p_ZZ14fitness_kernelE13local_vectors_18_ce0_local : STD_LOGIC;
    signal p_ZZ14fitness_kernelE13local_vectors_17_we0_local : STD_LOGIC;
    signal ap_predicate_pred353_state4 : BOOLEAN;
    signal p_ZZ14fitness_kernelE13local_vectors_17_ce0_local : STD_LOGIC;
    signal p_ZZ14fitness_kernelE13local_vectors_16_we0_local : STD_LOGIC;
    signal ap_predicate_pred367_state4 : BOOLEAN;
    signal p_ZZ14fitness_kernelE13local_vectors_16_ce0_local : STD_LOGIC;
    signal p_ZZ14fitness_kernelE13local_vectors_15_we0_local : STD_LOGIC;
    signal ap_predicate_pred381_state4 : BOOLEAN;
    signal p_ZZ14fitness_kernelE13local_vectors_15_ce0_local : STD_LOGIC;
    signal p_ZZ14fitness_kernelE13local_vectors_14_we0_local : STD_LOGIC;
    signal ap_predicate_pred395_state4 : BOOLEAN;
    signal p_ZZ14fitness_kernelE13local_vectors_14_ce0_local : STD_LOGIC;
    signal p_ZZ14fitness_kernelE13local_vectors_13_we0_local : STD_LOGIC;
    signal ap_predicate_pred409_state4 : BOOLEAN;
    signal p_ZZ14fitness_kernelE13local_vectors_13_ce0_local : STD_LOGIC;
    signal p_ZZ14fitness_kernelE13local_vectors_12_we0_local : STD_LOGIC;
    signal ap_predicate_pred423_state4 : BOOLEAN;
    signal p_ZZ14fitness_kernelE13local_vectors_12_ce0_local : STD_LOGIC;
    signal p_ZZ14fitness_kernelE13local_vectors_11_we0_local : STD_LOGIC;
    signal ap_predicate_pred437_state4 : BOOLEAN;
    signal p_ZZ14fitness_kernelE13local_vectors_11_ce0_local : STD_LOGIC;
    signal p_ZZ14fitness_kernelE13local_vectors_10_we0_local : STD_LOGIC;
    signal ap_predicate_pred451_state4 : BOOLEAN;
    signal p_ZZ14fitness_kernelE13local_vectors_10_ce0_local : STD_LOGIC;
    signal local_vectors_9_we0_local : STD_LOGIC;
    signal ap_predicate_pred465_state4 : BOOLEAN;
    signal local_vectors_9_ce0_local : STD_LOGIC;
    signal local_vectors_8_we0_local : STD_LOGIC;
    signal ap_predicate_pred479_state4 : BOOLEAN;
    signal local_vectors_8_ce0_local : STD_LOGIC;
    signal local_vectors_7_we0_local : STD_LOGIC;
    signal ap_predicate_pred493_state4 : BOOLEAN;
    signal local_vectors_7_ce0_local : STD_LOGIC;
    signal local_vectors_6_we0_local : STD_LOGIC;
    signal ap_predicate_pred507_state4 : BOOLEAN;
    signal local_vectors_6_ce0_local : STD_LOGIC;
    signal local_vectors_5_we0_local : STD_LOGIC;
    signal ap_predicate_pred521_state4 : BOOLEAN;
    signal local_vectors_5_ce0_local : STD_LOGIC;
    signal local_vectors_4_we0_local : STD_LOGIC;
    signal ap_predicate_pred535_state4 : BOOLEAN;
    signal local_vectors_4_ce0_local : STD_LOGIC;
    signal local_vectors_3_we0_local : STD_LOGIC;
    signal ap_predicate_pred549_state4 : BOOLEAN;
    signal local_vectors_3_ce0_local : STD_LOGIC;
    signal local_vectors_2_we0_local : STD_LOGIC;
    signal ap_predicate_pred563_state4 : BOOLEAN;
    signal local_vectors_2_ce0_local : STD_LOGIC;
    signal local_vectors_1_we0_local : STD_LOGIC;
    signal ap_predicate_pred577_state4 : BOOLEAN;
    signal local_vectors_1_ce0_local : STD_LOGIC;
    signal local_vectors_we0_local : STD_LOGIC;
    signal ap_predicate_pred591_state4 : BOOLEAN;
    signal local_vectors_ce0_local : STD_LOGIC;
    signal p_ZZ14fitness_kernelE13local_vectors_19_we0_local : STD_LOGIC;
    signal ap_predicate_pred640_state4 : BOOLEAN;
    signal p_ZZ14fitness_kernelE13local_vectors_19_ce0_local : STD_LOGIC;
    signal zext_ln59_fu_458_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln59_1_fu_483_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln59_2_fu_477_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_fu_526_p4 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fitness_kernel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component fitness_kernel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    i_fu_152_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_152 <= ap_const_lv31_0;
                elsif (((icmp_ln59_fu_462_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    i_fu_152 <= add_ln59_fu_467_p2;
                end if;
            end if; 
        end if;
    end process;

    phi_mul_fu_148_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    phi_mul_fu_148 <= ap_const_lv63_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    phi_mul_fu_148 <= add_ln59_1_fu_520_p2;
                end if;
            end if; 
        end if;
    end process;

    phi_urem_fu_144_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    phi_urem_fu_144 <= ap_const_lv31_0;
                elsif (((icmp_ln59_fu_462_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    phi_urem_fu_144 <= select_ln59_fu_489_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                trunc_ln59_reg_600 <= trunc_ln59_fu_473_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                    ap_predicate_pred339_state4 <= (trunc_ln59_reg_600 = ap_const_lv5_12);
                    ap_predicate_pred353_state4 <= (trunc_ln59_reg_600 = ap_const_lv5_11);
                    ap_predicate_pred367_state4 <= (trunc_ln59_reg_600 = ap_const_lv5_10);
                    ap_predicate_pred381_state4 <= (trunc_ln59_reg_600 = ap_const_lv5_F);
                    ap_predicate_pred395_state4 <= (trunc_ln59_reg_600 = ap_const_lv5_E);
                    ap_predicate_pred409_state4 <= (trunc_ln59_reg_600 = ap_const_lv5_D);
                    ap_predicate_pred423_state4 <= (trunc_ln59_reg_600 = ap_const_lv5_C);
                    ap_predicate_pred437_state4 <= (trunc_ln59_reg_600 = ap_const_lv5_B);
                    ap_predicate_pred451_state4 <= (trunc_ln59_reg_600 = ap_const_lv5_A);
                    ap_predicate_pred465_state4 <= (trunc_ln59_reg_600 = ap_const_lv5_9);
                    ap_predicate_pred479_state4 <= (trunc_ln59_reg_600 = ap_const_lv5_8);
                    ap_predicate_pred493_state4 <= (trunc_ln59_reg_600 = ap_const_lv5_7);
                    ap_predicate_pred507_state4 <= (trunc_ln59_reg_600 = ap_const_lv5_6);
                    ap_predicate_pred521_state4 <= (trunc_ln59_reg_600 = ap_const_lv5_5);
                    ap_predicate_pred535_state4 <= (trunc_ln59_reg_600 = ap_const_lv5_4);
                    ap_predicate_pred549_state4 <= (trunc_ln59_reg_600 = ap_const_lv5_3);
                    ap_predicate_pred563_state4 <= (trunc_ln59_reg_600 = ap_const_lv5_2);
                    ap_predicate_pred577_state4 <= (trunc_ln59_reg_600 = ap_const_lv5_1);
                    ap_predicate_pred591_state4 <= (trunc_ln59_reg_600 = ap_const_lv5_0);
                    ap_predicate_pred640_state4 <= (not((trunc_ln59_reg_600 = ap_const_lv5_0)) and not((trunc_ln59_reg_600 = ap_const_lv5_1)) and not((trunc_ln59_reg_600 = ap_const_lv5_2)) and not((trunc_ln59_reg_600 = ap_const_lv5_3)) and not((trunc_ln59_reg_600 = ap_const_lv5_4)) and not((trunc_ln59_reg_600 = ap_const_lv5_5)) and not((trunc_ln59_reg_600 = ap_const_lv5_6)) and not((trunc_ln59_reg_600 = ap_const_lv5_7)) and not((trunc_ln59_reg_600 = ap_const_lv5_8)) and not((trunc_ln59_reg_600 = ap_const_lv5_9)) and not((trunc_ln59_reg_600 = ap_const_lv5_A)) and not((trunc_ln59_reg_600 = ap_const_lv5_B)) and not((trunc_ln59_reg_600 = ap_const_lv5_C)) and not((trunc_ln59_reg_600 = ap_const_lv5_D)) and not((trunc_ln59_reg_600 = ap_const_lv5_E)) and not((trunc_ln59_reg_600 = ap_const_lv5_F)) and not((trunc_ln59_reg_600 = ap_const_lv5_10)) and not((trunc_ln59_reg_600 = ap_const_lv5_11)) and not((trunc_ln59_reg_600 = ap_const_lv5_12)));
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                bitcast_ln61_reg_604 <= bitcast_ln61_fu_513_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln59_1_fu_520_p2 <= std_logic_vector(unsigned(phi_mul_fu_148) + unsigned(ap_const_lv63_CCCCCCCD));
    add_ln59_2_fu_477_p2 <= std_logic_vector(unsigned(phi_urem_fu_144) + unsigned(ap_const_lv31_1));
    add_ln59_fu_467_p2 <= std_logic_vector(unsigned(i_fu_152) + unsigned(ap_const_lv31_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem_vec_0_RVALID)
    begin
                ap_block_pp0_stage0_11001 <= ((m_axi_gmem_vec_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem_vec_0_RVALID)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((m_axi_gmem_vec_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem_vec_0_RVALID)
    begin
                ap_block_pp0_stage0_subdone <= ((m_axi_gmem_vec_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln59_fu_462_p2)
    begin
        if (((icmp_ln59_fu_462_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    bitcast_ln61_fu_513_p1 <= m_axi_gmem_vec_0_RDATA;

    gmem_vec_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem_vec_0_RVALID, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            gmem_vec_blk_n_R <= m_axi_gmem_vec_0_RVALID;
        else 
            gmem_vec_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln59_1_fu_483_p2 <= "1" when (phi_urem_fu_144 = ap_const_lv31_13) else "0";
    icmp_ln59_fu_462_p2 <= "1" when (signed(zext_ln59_fu_458_p1) < signed(total)) else "0";
    local_vectors_1_address0 <= zext_ln59_1_fu_536_p1(9 - 1 downto 0);
    local_vectors_1_ce0 <= local_vectors_1_ce0_local;

    local_vectors_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            local_vectors_1_ce0_local <= ap_const_logic_1;
        else 
            local_vectors_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_vectors_1_d0 <= bitcast_ln61_reg_604;
    local_vectors_1_we0 <= local_vectors_1_we0_local;

    local_vectors_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_predicate_pred577_state4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_predicate_pred577_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            local_vectors_1_we0_local <= ap_const_logic_1;
        else 
            local_vectors_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_vectors_2_address0 <= zext_ln59_1_fu_536_p1(9 - 1 downto 0);
    local_vectors_2_ce0 <= local_vectors_2_ce0_local;

    local_vectors_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            local_vectors_2_ce0_local <= ap_const_logic_1;
        else 
            local_vectors_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_vectors_2_d0 <= bitcast_ln61_reg_604;
    local_vectors_2_we0 <= local_vectors_2_we0_local;

    local_vectors_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_predicate_pred563_state4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_predicate_pred563_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            local_vectors_2_we0_local <= ap_const_logic_1;
        else 
            local_vectors_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_vectors_3_address0 <= zext_ln59_1_fu_536_p1(9 - 1 downto 0);
    local_vectors_3_ce0 <= local_vectors_3_ce0_local;

    local_vectors_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            local_vectors_3_ce0_local <= ap_const_logic_1;
        else 
            local_vectors_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_vectors_3_d0 <= bitcast_ln61_reg_604;
    local_vectors_3_we0 <= local_vectors_3_we0_local;

    local_vectors_3_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_predicate_pred549_state4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_predicate_pred549_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            local_vectors_3_we0_local <= ap_const_logic_1;
        else 
            local_vectors_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_vectors_4_address0 <= zext_ln59_1_fu_536_p1(9 - 1 downto 0);
    local_vectors_4_ce0 <= local_vectors_4_ce0_local;

    local_vectors_4_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            local_vectors_4_ce0_local <= ap_const_logic_1;
        else 
            local_vectors_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_vectors_4_d0 <= bitcast_ln61_reg_604;
    local_vectors_4_we0 <= local_vectors_4_we0_local;

    local_vectors_4_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_predicate_pred535_state4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_predicate_pred535_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            local_vectors_4_we0_local <= ap_const_logic_1;
        else 
            local_vectors_4_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_vectors_5_address0 <= zext_ln59_1_fu_536_p1(9 - 1 downto 0);
    local_vectors_5_ce0 <= local_vectors_5_ce0_local;

    local_vectors_5_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            local_vectors_5_ce0_local <= ap_const_logic_1;
        else 
            local_vectors_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_vectors_5_d0 <= bitcast_ln61_reg_604;
    local_vectors_5_we0 <= local_vectors_5_we0_local;

    local_vectors_5_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_predicate_pred521_state4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_predicate_pred521_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            local_vectors_5_we0_local <= ap_const_logic_1;
        else 
            local_vectors_5_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_vectors_6_address0 <= zext_ln59_1_fu_536_p1(9 - 1 downto 0);
    local_vectors_6_ce0 <= local_vectors_6_ce0_local;

    local_vectors_6_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            local_vectors_6_ce0_local <= ap_const_logic_1;
        else 
            local_vectors_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_vectors_6_d0 <= bitcast_ln61_reg_604;
    local_vectors_6_we0 <= local_vectors_6_we0_local;

    local_vectors_6_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_predicate_pred507_state4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_predicate_pred507_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            local_vectors_6_we0_local <= ap_const_logic_1;
        else 
            local_vectors_6_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_vectors_7_address0 <= zext_ln59_1_fu_536_p1(9 - 1 downto 0);
    local_vectors_7_ce0 <= local_vectors_7_ce0_local;

    local_vectors_7_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            local_vectors_7_ce0_local <= ap_const_logic_1;
        else 
            local_vectors_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_vectors_7_d0 <= bitcast_ln61_reg_604;
    local_vectors_7_we0 <= local_vectors_7_we0_local;

    local_vectors_7_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_predicate_pred493_state4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_predicate_pred493_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            local_vectors_7_we0_local <= ap_const_logic_1;
        else 
            local_vectors_7_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_vectors_8_address0 <= zext_ln59_1_fu_536_p1(9 - 1 downto 0);
    local_vectors_8_ce0 <= local_vectors_8_ce0_local;

    local_vectors_8_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            local_vectors_8_ce0_local <= ap_const_logic_1;
        else 
            local_vectors_8_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_vectors_8_d0 <= bitcast_ln61_reg_604;
    local_vectors_8_we0 <= local_vectors_8_we0_local;

    local_vectors_8_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_predicate_pred479_state4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_predicate_pred479_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            local_vectors_8_we0_local <= ap_const_logic_1;
        else 
            local_vectors_8_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_vectors_9_address0 <= zext_ln59_1_fu_536_p1(9 - 1 downto 0);
    local_vectors_9_ce0 <= local_vectors_9_ce0_local;

    local_vectors_9_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            local_vectors_9_ce0_local <= ap_const_logic_1;
        else 
            local_vectors_9_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_vectors_9_d0 <= bitcast_ln61_reg_604;
    local_vectors_9_we0 <= local_vectors_9_we0_local;

    local_vectors_9_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_predicate_pred465_state4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_predicate_pred465_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            local_vectors_9_we0_local <= ap_const_logic_1;
        else 
            local_vectors_9_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_vectors_address0 <= zext_ln59_1_fu_536_p1(9 - 1 downto 0);
    local_vectors_ce0 <= local_vectors_ce0_local;

    local_vectors_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            local_vectors_ce0_local <= ap_const_logic_1;
        else 
            local_vectors_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_vectors_d0 <= bitcast_ln61_reg_604;
    local_vectors_we0 <= local_vectors_we0_local;

    local_vectors_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_predicate_pred591_state4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_predicate_pred591_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            local_vectors_we0_local <= ap_const_logic_1;
        else 
            local_vectors_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_vec_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem_vec_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_vec_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_vec_0_ARID <= ap_const_lv1_0;
    m_axi_gmem_vec_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem_vec_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_vec_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_vec_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_vec_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_vec_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_vec_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem_vec_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem_vec_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_vec_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_vec_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_vec_0_AWID <= ap_const_lv1_0;
    m_axi_gmem_vec_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_vec_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_vec_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_vec_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_vec_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_vec_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_vec_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_vec_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem_vec_0_BREADY <= ap_const_logic_0;

    m_axi_gmem_vec_0_RREADY_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            m_axi_gmem_vec_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem_vec_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_vec_0_WDATA <= ap_const_lv32_0;
    m_axi_gmem_vec_0_WID <= ap_const_lv1_0;
    m_axi_gmem_vec_0_WLAST <= ap_const_logic_0;
    m_axi_gmem_vec_0_WSTRB <= ap_const_lv4_0;
    m_axi_gmem_vec_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem_vec_0_WVALID <= ap_const_logic_0;
    p_ZZ14fitness_kernelE13local_vectors_10_address0 <= zext_ln59_1_fu_536_p1(9 - 1 downto 0);
    p_ZZ14fitness_kernelE13local_vectors_10_ce0 <= p_ZZ14fitness_kernelE13local_vectors_10_ce0_local;

    p_ZZ14fitness_kernelE13local_vectors_10_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            p_ZZ14fitness_kernelE13local_vectors_10_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ14fitness_kernelE13local_vectors_10_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ14fitness_kernelE13local_vectors_10_d0 <= bitcast_ln61_reg_604;
    p_ZZ14fitness_kernelE13local_vectors_10_we0 <= p_ZZ14fitness_kernelE13local_vectors_10_we0_local;

    p_ZZ14fitness_kernelE13local_vectors_10_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_predicate_pred451_state4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_predicate_pred451_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            p_ZZ14fitness_kernelE13local_vectors_10_we0_local <= ap_const_logic_1;
        else 
            p_ZZ14fitness_kernelE13local_vectors_10_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ14fitness_kernelE13local_vectors_11_address0 <= zext_ln59_1_fu_536_p1(9 - 1 downto 0);
    p_ZZ14fitness_kernelE13local_vectors_11_ce0 <= p_ZZ14fitness_kernelE13local_vectors_11_ce0_local;

    p_ZZ14fitness_kernelE13local_vectors_11_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            p_ZZ14fitness_kernelE13local_vectors_11_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ14fitness_kernelE13local_vectors_11_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ14fitness_kernelE13local_vectors_11_d0 <= bitcast_ln61_reg_604;
    p_ZZ14fitness_kernelE13local_vectors_11_we0 <= p_ZZ14fitness_kernelE13local_vectors_11_we0_local;

    p_ZZ14fitness_kernelE13local_vectors_11_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_predicate_pred437_state4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_predicate_pred437_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            p_ZZ14fitness_kernelE13local_vectors_11_we0_local <= ap_const_logic_1;
        else 
            p_ZZ14fitness_kernelE13local_vectors_11_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ14fitness_kernelE13local_vectors_12_address0 <= zext_ln59_1_fu_536_p1(9 - 1 downto 0);
    p_ZZ14fitness_kernelE13local_vectors_12_ce0 <= p_ZZ14fitness_kernelE13local_vectors_12_ce0_local;

    p_ZZ14fitness_kernelE13local_vectors_12_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            p_ZZ14fitness_kernelE13local_vectors_12_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ14fitness_kernelE13local_vectors_12_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ14fitness_kernelE13local_vectors_12_d0 <= bitcast_ln61_reg_604;
    p_ZZ14fitness_kernelE13local_vectors_12_we0 <= p_ZZ14fitness_kernelE13local_vectors_12_we0_local;

    p_ZZ14fitness_kernelE13local_vectors_12_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_predicate_pred423_state4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_predicate_pred423_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            p_ZZ14fitness_kernelE13local_vectors_12_we0_local <= ap_const_logic_1;
        else 
            p_ZZ14fitness_kernelE13local_vectors_12_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ14fitness_kernelE13local_vectors_13_address0 <= zext_ln59_1_fu_536_p1(9 - 1 downto 0);
    p_ZZ14fitness_kernelE13local_vectors_13_ce0 <= p_ZZ14fitness_kernelE13local_vectors_13_ce0_local;

    p_ZZ14fitness_kernelE13local_vectors_13_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            p_ZZ14fitness_kernelE13local_vectors_13_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ14fitness_kernelE13local_vectors_13_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ14fitness_kernelE13local_vectors_13_d0 <= bitcast_ln61_reg_604;
    p_ZZ14fitness_kernelE13local_vectors_13_we0 <= p_ZZ14fitness_kernelE13local_vectors_13_we0_local;

    p_ZZ14fitness_kernelE13local_vectors_13_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_predicate_pred409_state4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_predicate_pred409_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            p_ZZ14fitness_kernelE13local_vectors_13_we0_local <= ap_const_logic_1;
        else 
            p_ZZ14fitness_kernelE13local_vectors_13_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ14fitness_kernelE13local_vectors_14_address0 <= zext_ln59_1_fu_536_p1(9 - 1 downto 0);
    p_ZZ14fitness_kernelE13local_vectors_14_ce0 <= p_ZZ14fitness_kernelE13local_vectors_14_ce0_local;

    p_ZZ14fitness_kernelE13local_vectors_14_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            p_ZZ14fitness_kernelE13local_vectors_14_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ14fitness_kernelE13local_vectors_14_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ14fitness_kernelE13local_vectors_14_d0 <= bitcast_ln61_reg_604;
    p_ZZ14fitness_kernelE13local_vectors_14_we0 <= p_ZZ14fitness_kernelE13local_vectors_14_we0_local;

    p_ZZ14fitness_kernelE13local_vectors_14_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_predicate_pred395_state4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_predicate_pred395_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            p_ZZ14fitness_kernelE13local_vectors_14_we0_local <= ap_const_logic_1;
        else 
            p_ZZ14fitness_kernelE13local_vectors_14_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ14fitness_kernelE13local_vectors_15_address0 <= zext_ln59_1_fu_536_p1(9 - 1 downto 0);
    p_ZZ14fitness_kernelE13local_vectors_15_ce0 <= p_ZZ14fitness_kernelE13local_vectors_15_ce0_local;

    p_ZZ14fitness_kernelE13local_vectors_15_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            p_ZZ14fitness_kernelE13local_vectors_15_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ14fitness_kernelE13local_vectors_15_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ14fitness_kernelE13local_vectors_15_d0 <= bitcast_ln61_reg_604;
    p_ZZ14fitness_kernelE13local_vectors_15_we0 <= p_ZZ14fitness_kernelE13local_vectors_15_we0_local;

    p_ZZ14fitness_kernelE13local_vectors_15_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_predicate_pred381_state4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_predicate_pred381_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            p_ZZ14fitness_kernelE13local_vectors_15_we0_local <= ap_const_logic_1;
        else 
            p_ZZ14fitness_kernelE13local_vectors_15_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ14fitness_kernelE13local_vectors_16_address0 <= zext_ln59_1_fu_536_p1(9 - 1 downto 0);
    p_ZZ14fitness_kernelE13local_vectors_16_ce0 <= p_ZZ14fitness_kernelE13local_vectors_16_ce0_local;

    p_ZZ14fitness_kernelE13local_vectors_16_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            p_ZZ14fitness_kernelE13local_vectors_16_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ14fitness_kernelE13local_vectors_16_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ14fitness_kernelE13local_vectors_16_d0 <= bitcast_ln61_reg_604;
    p_ZZ14fitness_kernelE13local_vectors_16_we0 <= p_ZZ14fitness_kernelE13local_vectors_16_we0_local;

    p_ZZ14fitness_kernelE13local_vectors_16_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_predicate_pred367_state4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_predicate_pred367_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            p_ZZ14fitness_kernelE13local_vectors_16_we0_local <= ap_const_logic_1;
        else 
            p_ZZ14fitness_kernelE13local_vectors_16_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ14fitness_kernelE13local_vectors_17_address0 <= zext_ln59_1_fu_536_p1(9 - 1 downto 0);
    p_ZZ14fitness_kernelE13local_vectors_17_ce0 <= p_ZZ14fitness_kernelE13local_vectors_17_ce0_local;

    p_ZZ14fitness_kernelE13local_vectors_17_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            p_ZZ14fitness_kernelE13local_vectors_17_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ14fitness_kernelE13local_vectors_17_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ14fitness_kernelE13local_vectors_17_d0 <= bitcast_ln61_reg_604;
    p_ZZ14fitness_kernelE13local_vectors_17_we0 <= p_ZZ14fitness_kernelE13local_vectors_17_we0_local;

    p_ZZ14fitness_kernelE13local_vectors_17_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_predicate_pred353_state4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_predicate_pred353_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            p_ZZ14fitness_kernelE13local_vectors_17_we0_local <= ap_const_logic_1;
        else 
            p_ZZ14fitness_kernelE13local_vectors_17_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ14fitness_kernelE13local_vectors_18_address0 <= zext_ln59_1_fu_536_p1(9 - 1 downto 0);
    p_ZZ14fitness_kernelE13local_vectors_18_ce0 <= p_ZZ14fitness_kernelE13local_vectors_18_ce0_local;

    p_ZZ14fitness_kernelE13local_vectors_18_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            p_ZZ14fitness_kernelE13local_vectors_18_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ14fitness_kernelE13local_vectors_18_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ14fitness_kernelE13local_vectors_18_d0 <= bitcast_ln61_reg_604;
    p_ZZ14fitness_kernelE13local_vectors_18_we0 <= p_ZZ14fitness_kernelE13local_vectors_18_we0_local;

    p_ZZ14fitness_kernelE13local_vectors_18_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_predicate_pred339_state4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_predicate_pred339_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            p_ZZ14fitness_kernelE13local_vectors_18_we0_local <= ap_const_logic_1;
        else 
            p_ZZ14fitness_kernelE13local_vectors_18_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ14fitness_kernelE13local_vectors_19_address0 <= zext_ln59_1_fu_536_p1(9 - 1 downto 0);
    p_ZZ14fitness_kernelE13local_vectors_19_ce0 <= p_ZZ14fitness_kernelE13local_vectors_19_ce0_local;

    p_ZZ14fitness_kernelE13local_vectors_19_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            p_ZZ14fitness_kernelE13local_vectors_19_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ14fitness_kernelE13local_vectors_19_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ14fitness_kernelE13local_vectors_19_d0 <= bitcast_ln61_reg_604;
    p_ZZ14fitness_kernelE13local_vectors_19_we0 <= p_ZZ14fitness_kernelE13local_vectors_19_we0_local;

    p_ZZ14fitness_kernelE13local_vectors_19_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_predicate_pred640_state4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_predicate_pred640_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            p_ZZ14fitness_kernelE13local_vectors_19_we0_local <= ap_const_logic_1;
        else 
            p_ZZ14fitness_kernelE13local_vectors_19_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln59_fu_489_p3 <= 
        ap_const_lv31_0 when (icmp_ln59_1_fu_483_p2(0) = '1') else 
        add_ln59_2_fu_477_p2;
    tmp_fu_526_p4 <= phi_mul_fu_148(62 downto 36);
    trunc_ln59_fu_473_p1 <= phi_urem_fu_144(5 - 1 downto 0);
    zext_ln59_1_fu_536_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_526_p4),64));
    zext_ln59_fu_458_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_fu_152),32));
end behav;
